CREATE TABLE City(
    city_id INT PRIMARY KEY IDENTITY (1,1);
    city_name VARCHAR(255) NOT NULL,
    country_name VARCHAR(255) NOT NULL,
);
CREATE SEQUENCE EMPLOYEE_SEQUENCE START WITH 1 INCREMENT BY 1;
